### PR TITLE
docs: Add documentation in the repo

### PR DESCRIPTION
**Pull request by alistair23**
The GitHub wiki does't allow others to contribute to the documentation.
Although the docuement is very useful it ends up being a little bare in
some apsects. This PR tries to add more details to the documentation to
help people get started. It also moves the docs into the project so that
it is easier for others to contibute.

The idea here is to move all the documentation accross if this is
accepted.

Signed-off-by: Alistair Francis <alistair@alistair23.me>

### CODE REVIEW

**Comment by tulir** [comment]
Huh? The wiki should definitely allow others to contribute, that's one of the main reasons I'm using the wiki instead of the readme.

Wiki editing was/is not restricted to collaborators only in the settings:
image

**Comment by alistair23** [comment]
Ah, yeah  you are right anyone can edit the wiki. That is very trusting :)

Their is still no PR interface for doc changes which is a downside. If you prefer I can just edit the wiki instead.

**Comment by tulir** [comment]
Yes, the wiki is the place for the docs

**Comment by alistair23** [comment]
I just updated the wiki then

**Pull request closed without merging**
