### PR TITLE
set default permission to invite bots to matrix room of whatsapp-bridge

### PR DESCRIPTION
**Pull request by progserega**
This patch allow matrix user (which use whatsapp-bridge) invite to room any other bots, which can help matrix user. 
For example - bot, which translate voice messages to text:
https://github.com/progserega/voice2textMatrix

### CODE REVIEW

**Comment by tulir** [comment]
This should probably be a config option, the default power levels are intended to be so users can only do bridgeable things

**Comment by progserega** [comment]
Okey. I will try add config option for this.

**Comment by MurzNN** [comment]
Maybe better will be add command to whatsapp bot for extend user privileges of current room on demand via `!whatsappbot extend-permissions`? Or do invite/actions kick via bot commands, something like `!whatsappbot invite-matrix-user`

**Comment by progserega** [comment]
Add `allow_user_invite` option to config. Default value is false.

**Comment by MurzNN** [comment]
Does it update permissions of already created bridged rooms, or apply only to new rooms?

**Comment by tulir** [comment]
You can delete the old room (`!wa delete-portal` for group chats and just leave the room for private chats)

**Comment by uvinduperera** [comment]
> 
> 
> Add `allow_user_invite` option to config. Default value is false.

Do we need to set value as true?

**Pull request merged**
